cd /var/www/phplib/bat
php ./daily_data_import.php ikkatsu_1.csv
php ./daily_data_import.php ikkatsu_2.csv
php ./daily_data_import.php ikkatsu_3.csv
php ./daily_data_import.php ikkatsu_4.csv
php ./daily_data_import.php ikkatsu_5.csv
php ./daily_data_import.php ikkatsu_6.csv
php ./daily_data_import.php ikkatsu_7.csv
php ./daily_data_import.php ikkatsu_8.csv
php ./daily_data_import.php ikkatsu_9.csv
php ./daily_data_import.php ikkatsu_10.csv
php ./daily_data_import.php ikkatsu_11.csv
php ./daily_data_import.php ikkatsu_12.csv
php ./daily_data_import.php ikkatsu_13.csv
php ./daily_data_import.php ikkatsu_14.csv
php ./daily_data_import.php ikkatsu_15.csv
php ./daily_data_import.php ikkatsu_16.csv
php ./daily_data_import.php ikkatsu_17.csv
php ./daily_data_import.php ikkatsu_18.csv
php ./daily_data_import.php ikkatsu_19.csv
php ./daily_data_import.php ikkatsu_20.csv
php ./daily_data_import.php ikkatsu_21.csv
php ./daily_data_import.php ikkatsu_22.csv
php ./daily_data_import.php ikkatsu_23.csv
php ./daily_data_import.php ikkatsu_24.csv
php ./daily_data_import.php ikkatsu_25.csv
php ./daily_data_import.php ikkatsu_26.csv
php ./daily_data_import.php ikkatsu_27.csv
php ./daily_data_import.php ikkatsu_28.csv
php ./daily_data_import.php ikkatsu_29.csv
php ./daily_data_import.php ikkatsu_30.csv
php ./daily_data_import.php ikkatsu_31.csv
php ./daily_data_import.php ikkatsu_32.csv
php ./daily_data_import.php ikkatsu_33.csv
php ./daily_data_import.php ikkatsu_34.csv
php ./daily_data_import.php ikkatsu_35.csv
php ./daily_data_import.php ikkatsu_36.csv
php ./daily_data_import.php ikkatsu_37.csv
php ./daily_data_import.php ikkatsu_38.csv
php ./daily_data_import.php ikkatsu_39.csv
php ./daily_data_import.php ikkatsu_40.csv
php ./daily_data_import.php ikkatsu_41.csv
php ./daily_data_import.php ikkatsu_42.csv
php ./daily_data_import.php ikkatsu_43.csv
php ./daily_data_import.php ikkatsu_44.csv
php ./daily_data_import.php ikkatsu_45.csv
php ./daily_data_import.php ikkatsu_46.csv
php ./daily_data_import.php ikkatsu_47.csv
php ./daily_data_import.php ikkatsu_48.csv
php ./daily_data_import.php ikkatsu_49.csv
php ./daily_data_import.php ikkatsu_50.csv
php ./daily_data_import.php ikkatsu_51.csv
php ./daily_data_import.php ikkatsu_52.csv
php ./daily_data_import.php ikkatsu_53.csv
php ./daily_data_import.php ikkatsu_54.csv
php ./daily_data_import.php ikkatsu_55.csv
php ./daily_data_import.php ikkatsu_56.csv
php ./daily_data_import.php ikkatsu_57.csv
php ./daily_data_import.php ikkatsu_58.csv
php ./daily_data_import.php ikkatsu_59.csv
php ./daily_data_import.php ikkatsu_60.csv
php ./daily_data_import.php ikkatsu_61.csv
php ./daily_data_import.php ikkatsu_62.csv
php ./daily_data_import.php ikkatsu_63.csv
php ./daily_data_import.php ikkatsu_64.csv
php ./daily_data_import.php ikkatsu_65.csv
php ./daily_data_import.php ikkatsu_66.csv
php ./daily_data_import.php ikkatsu_67.csv
php ./daily_data_import.php ikkatsu_68.csv
php ./daily_data_import.php ikkatsu_69.csv
php ./daily_data_import.php ikkatsu_70.csv
php ./daily_data_import.php ikkatsu_71.csv
php ./daily_data_import.php ikkatsu_72.csv
php ./daily_data_import.php ikkatsu_73.csv
php ./daily_data_import.php ikkatsu_74.csv
php ./daily_data_import.php ikkatsu_75.csv
php ./daily_data_import.php ikkatsu_76.csv
php ./daily_data_import.php ikkatsu_77.csv
php ./daily_data_import.php ikkatsu_78.csv
php ./daily_data_import.php ikkatsu_79.csv
php ./daily_data_import.php ikkatsu_80.csv
php ./daily_data_import.php ikkatsu_81.csv
php ./daily_data_import.php ikkatsu_82.csv
php ./daily_data_import.php ikkatsu_83.csv
php ./daily_data_import.php ikkatsu_84.csv
php ./daily_data_import.php ikkatsu_85.csv
php ./daily_data_import.php ikkatsu_86.csv
php ./daily_data_import.php ikkatsu_87.csv
php ./daily_data_import.php ikkatsu_88.csv
php ./daily_data_import.php ikkatsu_89.csv
php ./daily_data_import.php ikkatsu_90.csv
php ./daily_data_import.php ikkatsu_91.csv
php ./daily_data_import.php ikkatsu_92.csv
php ./daily_data_import.php ikkatsu_93.csv
php ./daily_data_import.php ikkatsu_94.csv
php ./daily_data_import.php ikkatsu_95.csv
php ./daily_data_import.php ikkatsu_96.csv
php ./daily_data_import.php ikkatsu_97.csv
php ./daily_data_import.php ikkatsu_98.csv
php ./daily_data_import.php ikkatsu_99.csv
php ./daily_data_import.php ikkatsu_100.csv
php ./daily_data_import.php ikkatsu_101.csv
php ./daily_data_import.php ikkatsu_102.csv
php ./daily_data_import.php ikkatsu_103.csv
php ./daily_data_import.php ikkatsu_104.csv
php ./daily_data_import.php ikkatsu_105.csv
php ./daily_data_import.php ikkatsu_106.csv
php ./daily_data_import.php ikkatsu_107.csv
php ./daily_data_import.php ikkatsu_108.csv
php ./daily_data_import.php ikkatsu_109.csv
php ./daily_data_import.php ikkatsu_110.csv
php ./daily_data_import.php ikkatsu_111.csv
php ./daily_data_import.php ikkatsu_112.csv
php ./daily_data_import.php ikkatsu_113.csv
php ./daily_data_import.php ikkatsu_114.csv
php ./daily_data_import.php ikkatsu_115.csv
php ./daily_data_import.php ikkatsu_116.csv
php ./daily_data_import.php ikkatsu_117.csv
php ./daily_data_import.php ikkatsu_118.csv
php ./daily_data_import.php ikkatsu_119.csv
php ./daily_data_import.php ikkatsu_120.csv
php ./daily_data_import.php ikkatsu_121.csv
php ./daily_data_import.php ikkatsu_122.csv
php ./daily_data_import.php ikkatsu_123.csv
php ./daily_data_import.php ikkatsu_124.csv
php ./daily_data_import.php ikkatsu_125.csv
php ./daily_data_import.php ikkatsu_126.csv
php ./daily_data_import.php ikkatsu_127.csv
php ./daily_data_import.php ikkatsu_128.csv
php ./daily_data_import.php ikkatsu_129.csv
php ./daily_data_import.php ikkatsu_130.csv
php ./daily_data_import.php ikkatsu_131.csv
php ./daily_data_import.php ikkatsu_132.csv
php ./daily_data_import.php ikkatsu_133.csv
php ./daily_data_import.php ikkatsu_134.csv
php ./daily_data_import.php ikkatsu_135.csv
php ./daily_data_import.php ikkatsu_136.csv
php ./daily_data_import.php ikkatsu_137.csv
php ./daily_data_import.php ikkatsu_138.csv
php ./daily_data_import.php ikkatsu_139.csv
php ./daily_data_import.php ikkatsu_140.csv
php ./daily_data_import.php ikkatsu_141.csv
php ./daily_data_import.php ikkatsu_142.csv
php ./daily_data_import.php ikkatsu_143.csv
php ./daily_data_import.php ikkatsu_144.csv
php ./daily_data_import.php ikkatsu_145.csv
php ./daily_data_import.php ikkatsu_146.csv
php ./daily_data_import.php ikkatsu_147.csv
php ./daily_data_import.php ikkatsu_148.csv
php ./daily_data_import.php ikkatsu_149.csv
php ./daily_data_import.php ikkatsu_150.csv
php ./daily_data_import.php ikkatsu_151.csv
php ./daily_data_import.php ikkatsu_152.csv
php ./daily_data_import.php ikkatsu_153.csv
php ./daily_data_import.php ikkatsu_154.csv
php ./daily_data_import.php ikkatsu_155.csv
php ./daily_data_import.php ikkatsu_156.csv
php ./daily_data_import.php ikkatsu_157.csv
php ./daily_data_import.php ikkatsu_158.csv
php ./daily_data_import.php ikkatsu_159.csv
php ./daily_data_import.php ikkatsu_160.csv
php ./daily_data_import.php ikkatsu_161.csv
php ./daily_data_import.php ikkatsu_162.csv
php ./daily_data_import.php ikkatsu_163.csv
php ./daily_data_import.php ikkatsu_164.csv
php ./daily_data_import.php ikkatsu_165.csv
php ./daily_data_import.php ikkatsu_166.csv
php ./daily_data_import.php ikkatsu_167.csv
php ./daily_data_import.php ikkatsu_168.csv
php ./daily_data_import.php ikkatsu_169.csv
php ./daily_data_import.php ikkatsu_170.csv
php ./daily_data_import.php ikkatsu_171.csv
php ./daily_data_import.php ikkatsu_172.csv
php ./daily_data_import.php ikkatsu_173.csv
php ./daily_data_import.php ikkatsu_174.csv
php ./daily_data_import.php ikkatsu_175.csv
php ./daily_data_import.php ikkatsu_176.csv
php ./daily_data_import.php ikkatsu_177.csv
php ./daily_data_import.php ikkatsu_178.csv
php ./daily_data_import.php ikkatsu_179.csv
php ./daily_data_import.php ikkatsu_180.csv
php ./daily_data_import.php ikkatsu_181.csv
php ./daily_data_import.php ikkatsu_182.csv
php ./daily_data_import.php ikkatsu_183.csv
php ./daily_data_import.php ikkatsu_184.csv
php ./daily_data_import.php ikkatsu_185.csv
php ./daily_data_import.php ikkatsu_186.csv
php ./daily_data_import.php ikkatsu_187.csv
php ./daily_data_import.php ikkatsu_188.csv
php ./daily_data_import.php ikkatsu_189.csv
php ./daily_data_import.php ikkatsu_190.csv
php ./daily_data_import.php ikkatsu_191.csv
php ./daily_data_import.php ikkatsu_192.csv
php ./daily_data_import.php ikkatsu_193.csv
php ./daily_data_import.php ikkatsu_194.csv
php ./daily_data_import.php ikkatsu_195.csv
php ./daily_data_import.php ikkatsu_196.csv
php ./daily_data_import.php ikkatsu_197.csv
php ./daily_data_import.php ikkatsu_198.csv
php ./daily_data_import.php ikkatsu_199.csv
php ./daily_data_import.php ikkatsu_200.csv
php ./daily_data_import.php ikkatsu_201.csv
php ./daily_data_import.php ikkatsu_202.csv
php ./daily_data_import.php ikkatsu_203.csv
php ./daily_data_import.php ikkatsu_204.csv
php ./daily_data_import.php ikkatsu_205.csv
php ./daily_data_import.php ikkatsu_206.csv
php ./daily_data_import.php ikkatsu_207.csv
php ./daily_data_import.php ikkatsu_208.csv
php ./daily_data_import.php ikkatsu_209.csv
php ./daily_data_import.php ikkatsu_210.csv
php ./daily_data_import.php ikkatsu_211.csv
php ./daily_data_import.php ikkatsu_212.csv
php ./daily_data_import.php ikkatsu_213.csv
php ./daily_data_import.php ikkatsu_214.csv
php ./daily_data_import.php ikkatsu_215.csv
php ./daily_data_import.php ikkatsu_216.csv
php ./daily_data_import.php ikkatsu_217.csv
php ./daily_data_import.php ikkatsu_218.csv
php ./daily_data_import.php ikkatsu_219.csv
php ./daily_data_import.php ikkatsu_220.csv
php ./daily_data_import.php ikkatsu_221.csv
php ./daily_data_import.php ikkatsu_222.csv
php ./daily_data_import.php ikkatsu_223.csv
php ./daily_data_import.php ikkatsu_224.csv
php ./daily_data_import.php ikkatsu_225.csv
php ./daily_data_import.php ikkatsu_226.csv
php ./daily_data_import.php ikkatsu_227.csv
php ./daily_data_import.php ikkatsu_228.csv
php ./daily_data_import.php ikkatsu_229.csv
php ./daily_data_import.php ikkatsu_230.csv
php ./daily_data_import.php ikkatsu_231.csv
php ./daily_data_import.php ikkatsu_232.csv
php ./daily_data_import.php ikkatsu_233.csv
php ./daily_data_import.php ikkatsu_234.csv
php ./daily_data_import.php ikkatsu_235.csv
php ./daily_data_import.php ikkatsu_236.csv
php ./daily_data_import.php ikkatsu_237.csv
php ./daily_data_import.php ikkatsu_238.csv
php ./daily_data_import.php ikkatsu_239.csv
php ./daily_data_import.php ikkatsu_240.csv
php ./daily_data_import.php ikkatsu_241.csv
php ./daily_data_import.php ikkatsu_242.csv
php ./daily_data_import.php ikkatsu_243.csv
php ./daily_data_import.php ikkatsu_244.csv
php ./daily_data_import.php ikkatsu_245.csv
php ./daily_data_import.php ikkatsu_246.csv
php ./daily_data_import.php ikkatsu_247.csv
php ./daily_data_import.php ikkatsu_248.csv
php ./daily_data_import.php ikkatsu_249.csv
php ./daily_data_import.php ikkatsu_250.csv
php ./daily_data_import.php ikkatsu_251.csv
php ./daily_data_import.php ikkatsu_252.csv
php ./daily_data_import.php ikkatsu_253.csv
php ./daily_data_import.php ikkatsu_254.csv
php ./daily_data_import.php ikkatsu_255.csv
php ./daily_data_import.php ikkatsu_256.csv
php ./daily_data_import.php ikkatsu_257.csv
php ./daily_data_import.php ikkatsu_258.csv
php ./daily_data_import.php ikkatsu_259.csv
php ./daily_data_import.php ikkatsu_260.csv
php ./daily_data_import.php ikkatsu_261.csv
php ./daily_data_import.php ikkatsu_262.csv
php ./daily_data_import.php ikkatsu_263.csv
php ./daily_data_import.php ikkatsu_264.csv
php ./daily_data_import.php ikkatsu_265.csv
php ./daily_data_import.php ikkatsu_266.csv
php ./daily_data_import.php ikkatsu_267.csv
php ./daily_data_import.php ikkatsu_268.csv
php ./daily_data_import.php ikkatsu_269.csv
php ./daily_data_import.php ikkatsu_270.csv
php ./daily_data_import.php ikkatsu_271.csv
php ./daily_data_import.php ikkatsu_272.csv
php ./daily_data_import.php ikkatsu_273.csv
php ./daily_data_import.php ikkatsu_274.csv
php ./daily_data_import.php ikkatsu_275.csv
php ./daily_data_import.php ikkatsu_276.csv
php ./daily_data_import.php ikkatsu_277.csv
php ./daily_data_import.php ikkatsu_278.csv
php ./daily_data_import.php ikkatsu_279.csv
php ./daily_data_import.php ikkatsu_280.csv
php ./daily_data_import.php ikkatsu_281.csv
php ./daily_data_import.php ikkatsu_282.csv
php ./daily_data_import.php ikkatsu_283.csv
php ./daily_data_import.php ikkatsu_284.csv
php ./daily_data_import.php ikkatsu_285.csv
php ./daily_data_import.php ikkatsu_286.csv
php ./daily_data_import.php ikkatsu_287.csv
php ./daily_data_import.php ikkatsu_288.csv
php ./daily_data_import.php ikkatsu_289.csv
php ./daily_data_import.php ikkatsu_290.csv
php ./daily_data_import.php ikkatsu_291.csv
php ./daily_data_import.php ikkatsu_292.csv
php ./daily_data_import.php ikkatsu_293.csv
php ./daily_data_import.php ikkatsu_294.csv
php ./daily_data_import.php ikkatsu_295.csv
php ./daily_data_import.php ikkatsu_296.csv
php ./daily_data_import.php ikkatsu_297.csv
php ./daily_data_import.php ikkatsu_298.csv
php ./daily_data_import.php ikkatsu_299.csv
php ./daily_data_import.php ikkatsu_300.csv
php ./daily_data_import.php ikkatsu_301.csv
php ./daily_data_import.php ikkatsu_302.csv
php ./daily_data_import.php ikkatsu_303.csv
php ./daily_data_import.php ikkatsu_304.csv
php ./daily_data_import.php ikkatsu_305.csv
php ./daily_data_import.php ikkatsu_306.csv
php ./daily_data_import.php ikkatsu_307.csv
php ./daily_data_import.php ikkatsu_308.csv
php ./daily_data_import.php ikkatsu_309.csv
php ./daily_data_import.php ikkatsu_310.csv
php ./daily_data_import.php ikkatsu_311.csv
php ./daily_data_import.php ikkatsu_312.csv
php ./daily_data_import.php ikkatsu_313.csv
php ./daily_data_import.php ikkatsu_314.csv
php ./daily_data_import.php ikkatsu_315.csv
php ./daily_data_import.php ikkatsu_316.csv
php ./daily_data_import.php ikkatsu_317.csv
php ./daily_data_import.php ikkatsu_318.csv
php ./daily_data_import.php ikkatsu_319.csv
php ./daily_data_import.php ikkatsu_320.csv
php ./daily_data_import.php ikkatsu_321.csv
php ./daily_data_import.php ikkatsu_322.csv
php ./daily_data_import.php ikkatsu_323.csv
php ./daily_data_import.php ikkatsu_324.csv
php ./daily_data_import.php ikkatsu_325.csv
php ./daily_data_import.php ikkatsu_326.csv
php ./daily_data_import.php ikkatsu_327.csv
php ./daily_data_import.php ikkatsu_328.csv
php ./daily_data_import.php ikkatsu_329.csv
php ./daily_data_import.php ikkatsu_330.csv
php ./daily_data_import.php ikkatsu_331.csv
php ./daily_data_import.php ikkatsu_332.csv
php ./daily_data_import.php ikkatsu_333.csv
php ./daily_data_import.php ikkatsu_334.csv
php ./daily_data_import.php ikkatsu_335.csv
php ./daily_data_import.php ikkatsu_336.csv
php ./daily_data_import.php ikkatsu_337.csv
php ./daily_data_import.php ikkatsu_338.csv
php ./daily_data_import.php ikkatsu_339.csv
php ./daily_data_import.php ikkatsu_340.csv
php ./daily_data_import.php ikkatsu_341.csv
php ./daily_data_import.php ikkatsu_342.csv
php ./daily_data_import.php ikkatsu_343.csv
php ./daily_data_import.php ikkatsu_344.csv
php ./daily_data_import.php ikkatsu_345.csv
php ./daily_data_import.php ikkatsu_346.csv
php ./daily_data_import.php ikkatsu_347.csv
php ./daily_data_import.php ikkatsu_348.csv
php ./daily_data_import.php ikkatsu_349.csv
php ./daily_data_import.php ikkatsu_350.csv
php ./daily_data_import.php ikkatsu_351.csv
php ./daily_data_import.php ikkatsu_352.csv
php ./daily_data_import.php ikkatsu_353.csv
php ./daily_data_import.php ikkatsu_354.csv
php ./daily_data_import.php ikkatsu_355.csv
php ./daily_data_import.php ikkatsu_356.csv
php ./daily_data_import.php ikkatsu_357.csv
php ./daily_data_import.php ikkatsu_358.csv
php ./daily_data_import.php ikkatsu_359.csv
php ./daily_data_import.php ikkatsu_360.csv
php ./daily_data_import.php ikkatsu_361.csv
php ./daily_data_import.php ikkatsu_362.csv
php ./daily_data_import.php ikkatsu_363.csv
php ./daily_data_import.php ikkatsu_364.csv
php ./daily_data_import.php ikkatsu_365.csv
php ./daily_data_import.php ikkatsu_366.csv
php ./daily_data_import.php ikkatsu_367.csv
php ./daily_data_import.php ikkatsu_368.csv
php ./daily_data_import.php ikkatsu_369.csv
php ./daily_data_import.php ikkatsu_370.csv
php ./daily_data_import.php ikkatsu_371.csv
php ./daily_data_import.php ikkatsu_372.csv
php ./daily_data_import.php ikkatsu_373.csv
php ./daily_data_import.php ikkatsu_374.csv
php ./daily_data_import.php ikkatsu_375.csv
php ./daily_data_import.php ikkatsu_376.csv
php ./daily_data_import.php ikkatsu_377.csv
php ./daily_data_import.php ikkatsu_378.csv
php ./daily_data_import.php ikkatsu_379.csv
php ./daily_data_import.php ikkatsu_380.csv
php ./daily_data_import.php ikkatsu_381.csv
php ./daily_data_import.php ikkatsu_382.csv
php ./daily_data_import.php ikkatsu_383.csv
php ./daily_data_import.php ikkatsu_384.csv
php ./daily_data_import.php ikkatsu_385.csv
php ./daily_data_import.php ikkatsu_386.csv
php ./daily_data_import.php ikkatsu_387.csv
php ./daily_data_import.php ikkatsu_388.csv
php ./daily_data_import.php ikkatsu_389.csv
php ./daily_data_import.php ikkatsu_390.csv
php ./daily_data_import.php ikkatsu_391.csv
php ./daily_data_import.php ikkatsu_392.csv
php ./daily_data_import.php ikkatsu_393.csv
php ./daily_data_import.php ikkatsu_394.csv
